### ISSUE TITLE
类似项目

### ISSUE THREAD

**Issue by King-of-Infinite-Space** [CaoMeiYouRen/genshin-relation-graph#1]
刚发现这个项目。我前不久用cytoscape.js做了个类似的人物网络图。看了你的视频介绍，我当时也没搜索到类似项目，大概是好巧不巧时间刚好错开了。
https://github.com/King-of-Infinite-Space/genshin-social-network

**Comment by CaoMeiYouRen** [comment]
我看了下你的实现比我这个好多了，看上去更加舒服些，我之后也学习下
